const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const today = new Date(); today.setHours(0,0,0,0);
const iso = (date) => new Date(date.getTime() - date.getTimezoneOffset()*60000).toISOString().slice(0,10);
const addDays = (days) => { const d = new Date(today); d.setDate(d.getDate()+days); return iso(d); };

const defaultData = {
  projects: [
    {id:'algebra', name:'Álgebra lineal', area:'Universidad', color:'violet'},
    {id:'programacion', name:'Programación web', area:'Universidad', color:'blue'},
    {id:'aws', name:'AWS Cloud Practitioner', area:'Certificaciones', color:'orange'},
    {id:'ingles', name:'Inglés técnico', area:'Certificaciones', color:'green'}
  ],
  tasks: [
    {id:1,title:'Resolver ejercicios de matrices',project:'algebra',date:iso(today),priority:'high',type:'Práctica',notes:'Capítulo 3, ejercicios 1 al 12.',done:false},
    {id:2,title:'Ver lección de EC2 y tomar apuntes',project:'aws',date:iso(today),priority:'high',type:'Estudio',notes:'Módulo 4 del curso.',done:false},
    {id:3,title:'Leer documentación sobre Flexbox',project:'programacion',date:addDays(1),priority:'medium',type:'Lectura',notes:'Practicar con 3 ejercicios.',done:false},
    {id:4,title:'Entregar avance del proyecto',project:'programacion',date:addDays(3),priority:'high',type:'Entrega',notes:'Subir repositorio antes de las 23:59.',done:false},
    {id:5,title:'Simulador de examen AWS',project:'aws',date:addDays(5),priority:'medium',type:'Examen',notes:'Meta: 75% o más.',done:false}
  ]
};
let data = JSON.parse(localStorage.getItem('organiza-data')) || defaultData;
let activeFilter = 'all'; let calendarDate = new Date(today.getFullYear(), today.getMonth(), 1);
const save = () => localStorage.setItem('organiza-data', JSON.stringify(data));
const project = (id) => data.projects.find(p => p.id === id);
const dateText = (date) => new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short'}).format(new Date(date+'T12:00'));
const relativeDate = (date) => { const d = new Date(date+'T12:00'); const delta=Math.round((d-today)/86400000); return delta===0?'Hoy':delta===1?'Mañana':delta===-1?'Ayer':dateText(date); };
const sortTasks = (tasks) => [...tasks].sort((a,b) => (a.done-b.done) || a.date.localeCompare(b.date) || ({high:0,medium:1,low:2}[a.priority]-({high:0,medium:1,low:2}[b.priority])));

function taskHTML(t) { const p=project(t.project)||{name:'Sin curso',color:'violet'}; const overdue=!t.done && t.date<iso(today); return `<article class="task" style="--project-color:var(--${p.color})"><button class="check ${t.done?'done':''}" data-toggle="${t.id}" aria-label="Marcar tarea"></button><div class="task-main"><div class="task-title">${escapeHTML(t.title)}</div><div class="task-meta"><span class="badge">${p.name}</span><span>${t.type}</span></div></div><span class="priority" style="--priority-color:${t.priority==='high'?'#ef766d':t.priority==='medium'?'#f1ad56':'#6dbf9d'}"></span><span class="due ${overdue?'overdue':''}">${overdue?'Atrasada · ':''}${relativeDate(t.date)}</span><button class="delete" data-delete="${t.id}" title="Eliminar">×</button></article>`; }
function escapeHTML(str){const el=document.createElement('div');el.textContent=str;return el.innerHTML}
function renderProjects(){ const sections=['Universidad','Certificaciones']; $('#projectList').innerHTML=sections.map(area=>`<div class="area-label">${area}</div>${data.projects.filter(p=>p.area===area).map(p=>`<div class="project"><i class="dot" style="--project-color:var(--${p.color})"></i>${p.name}<small>${data.tasks.filter(t=>t.project===p.id&&!t.done).length}</small></div>`).join('')}`).join(''); }
function renderToday(){ const open=data.tasks.filter(t=>!t.done), todayTasks=sortTasks(open.filter(t=>t.date===iso(today))); const late=open.filter(t=>t.date<iso(today)); $('#todayCount').textContent=todayTasks.length; $('#dateLabel').textContent=new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long'}).format(today).replace(/^./,x=>x.toUpperCase()); $('#stats').innerHTML=[['✓',todayTasks.length,'tareas para hoy','#eeebff'],['◷',late.length,'tareas atrasadas','#fff1ea'],['◉',data.projects.length,'cursos activos','#e9f5ff']].map(x=>`<div class="stat"><div class="stat-icon" style="background:${x[3]}">${x[0]}</div><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join(''); $('#focusSubtitle').textContent=todayTasks.length?'Tus tareas importantes para hoy':'No tienes pendientes para hoy'; $('#focusTasks').innerHTML=todayTasks.length?todayTasks.map(taskHTML).join(''):`<div class="empty">Todo listo por hoy. Puedes adelantar algo de los próximos días ✦</div>`; const upcoming=sortTasks(open.filter(t=>t.date>iso(today))).slice(0,3); $('#upcoming').innerHTML=upcoming.length?upcoming.map(t=>{const p=project(t.project);return `<article class="upcoming-card" style="--project-color:var(--${p.color})"><span class="upcoming-date">${relativeDate(t.date).toUpperCase()}</span><h3>${escapeHTML(t.title)}</h3><p><i class="dot" style="display:inline-block;--project-color:var(--${p.color})"></i> ${p.name}</p></article>`}).join(''):'<div class="empty">No hay fechas próximas.</div>'; }
function renderAll(){const filterMap={all:()=>true,today:t=>t.date===iso(today),upcoming:t=>t.date>iso(today),overdue:t=>!t.done&&t.date<iso(today)};const tasks=sortTasks(data.tasks.filter(filterMap[activeFilter]));$('#allTasks').innerHTML=tasks.length?tasks.map(taskHTML).join(''):'<div class="empty">No hay tareas en esta vista.</div>';}
function renderCalendar(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth();$('#monthTitle').textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(calendarDate);const first=new Date(year,month,1), days=new Date(year,month+1,0).getDate(), start=(first.getDay()+6)%7;let html='';for(let i=0;i<start;i++)html+='<div class="day empty"></div>';for(let day=1;day<=days;day++){const date=iso(new Date(year,month,day));const tasks=data.tasks.filter(t=>t.date===date);html+=`<div class="day ${date===iso(today)?'today':''}"><span class="day-number">${day}</span>${tasks.slice(0,3).map(t=>{const p=project(t.project);return `<div class="calendar-task" style="--project-color:var(--${p.color})">${t.done?'✓ ':''}${escapeHTML(t.title)}</div>`}).join('')}${tasks.length>3?`<small>+${tasks.length-3} más</small>`:''}</div>`}$('#calendarDays').innerHTML=html;}
function render(){renderProjects();renderToday();renderAll();renderCalendar();}
function openTask(){const select=$('#taskProject');select.innerHTML=data.projects.map(p=>`<option value="${p.id}">${p.area} · ${p.name}</option>`).join('');$('#taskDate').value=iso(today);$('#taskModal').showModal();$('#taskTitle').focus();}
function bind(){ $$('[data-view]').forEach(b=>b.addEventListener('click',()=>{const view=b.dataset.view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#crumb').textContent=view==='today'?'MI PLANIFICACIÓN':view==='calendar'?'TU AGENDA':'MIS TAREAS';})); $('#addTask').onclick=openTask; $$('[data-add-task]').forEach(b=>b.onclick=openTask);$('#newProjectSide').onclick=()=>$('#projectModal').showModal();$('#taskForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const title=$('#taskTitle').value.trim();if(!title)return;e.preventDefault();data.tasks.push({id:Date.now(),title,project:$('#taskProject').value,date:$('#taskDate').value||iso(today),priority:$('#taskPriority').value,type:$('#taskType').value,notes:$('#taskNotes').value,done:false});save();$('#taskModal').close();e.target.reset();render();});$('#projectForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const name=$('#projectName').value.trim();if(!name)return;e.preventDefault();const id=`p${Date.now()}`;data.projects.push({id,name,area:$('#projectArea').value,color:$('#projectColor').value});save();$('#projectModal').close();e.target.reset();render();});document.addEventListener('click',e=>{const id=e.target.dataset.toggle;if(id){const t=data.tasks.find(t=>t.id===Number(id));t.done=!t.done;save();render()}const del=e.target.dataset.delete;if(del){data.tasks=data.tasks.filter(t=>t.id!==Number(del));save();render()}});$$('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderAll();});$('#prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('#themeToggle').onclick=()=>document.body.classList.toggle('dark');$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');}
bind();render();
